service: serverless-app
app: myapp
org: brgmnadam

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  region: us-east-1
  environment:
    CLIENT_ID: ${ssm:/login/clientId~true}
    CLIENT_SECRET: ${ssm:/login/clientSecret~true}
    USERS_TABLE_NAME: ${self:custom.usersTableName}
    WSS_TABLE_NAME: ${self:custom.wssTableName}
    # CLIENT_URL: https://github-app.adambergman.me
    CLIENT_URL: http://localhost:3000
    SERVER_URL: https://sls-github.adambergman.me
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:*
      Resource: '*'

plugins:
  - serverless-finch
  - serverless-domain-manager

custom:
  usersTableName: githubUsers
  wssTableName: socketUsers
  client:
    bucketName: github-app.adambergman.me
    distributionFolder: ../client/build
    indexDocument: index.html
    errorDocument: index.html
  customDomain:
    domainName: sls-github.adambergman.me
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    
functions:
  oauthCallback:
    handler: lambdas/oauthCallback.handler
    events:
      - http:
          path: /oauth/callback
          method: get
          cors: true
  index:
    handler: lambdas/index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  user:
    handler: lambdas/user.handler
    events:
      - http:
          path: /user
          method: post
          cors: true
  updateUser:
    handler: lambdas/updateUser.handler
    events:
      - http:
          path: /updateUser
          method: post
          cors: true
  getWebhook:
    handler: lambdas/getNotification.handler
    events:
      - http:
          path: /webhook
          method: post
          cors: true
  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-events:
    handler: lambdas/websockets/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    WebSocketUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.wssTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST